apiVersion: v1
kind: Service
metadata:
  name: eval-express-min
  labels:
    app.kubernetes.io/name: eval-express-min
    app.kubernetes.io/instance: eval-express-min
spec:
  type: NodePort
  selector:
    app: eval-express-min
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
